import type { Metadata } from "next";
import localFont from "next/font/local";
import BottomNavigation from "../components/MobileBottomNavigation";
import "./globals.css";

const MorabaFont = localFont({
  src: "/fonts/Morabba/ttf/Morabba-Black.ttf",
  display: "swap",
});
export const metadata: Metadata = {
  title: "DivarCP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body
        className={`bg-[#5D866C] lg:flex lg:items-center lg:justify-center min-h-screen ${MorabaFont.className}`}
      >
        <div
          className="
            w-full
            min-h-screen
            bg-[#F5F5F0]
            lg:w-97.5
            lg:h-211
            lg:min-h-0
            lg:rounded-[40px]
            lg:shadow-2xl
            flex
            flex-col
            overflow-hidden
          "
        >
          {/* Content */}
          <div className="flex-1 overflow-y-auto pb-14 lg:pb-0">{children}</div>

          {/* Desktop Bottom Nav (inside frame) */}
          <div className="hidden lg:block">
            <BottomNavigation />
          </div>
        </div>

        {/* Mobile Bottom Nav (fixed) */}
        <div className="lg:hidden">
          <BottomNavigation mobile />
        </div>
      </body>
    </html>
  );
}
