import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "DivarCP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body className="bg-[#5D866C] lg:flex lg:items-center lg:justify-center min-h-screen">
        <div
          className="
            w-full
            min-h-screen
            bg-white
            lg:min-h-0
            lg:max-w-[390px]
            lg:h-[844px]
            lg:rounded-[40px]
            lg:shadow-2xl
            overflow-hidden
          "
        >
          {children}
        </div>
      </body>
    </html>
  );
} 