import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body className="bg-neutral-900 flex items-center justify-center min-h-screen">

        <div
          className="
            w-full 
            max-w-[390px] 
            h-[844px] 
            bg-white 
            overflow-hidden
            lg:rounded-[40px] 
            lg:shadow-2xl
          "
        >
          {children}
        </div>

      </body>
    </html>
  );
}